# drone.io v0.4
# armhf

build:
    image: takawang/dind:$$arch
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/tmp:/var/tmp # for test
    privileged: true
    commands:
        #---------------------- PACKING -----------------------------------
        # build cache
        - docker build -t cache:$$arch -f release/Dockerfile.$$arch-cache .
        # build builder
        - docker build -t builder:$$arch --no-cache=true -f release/Dockerfile.$$arch-build .
        - docker run -itd --name=builder builder:$$arch
        # copy binary to release folder
        - docker cp builder:/usr/lib/libzmq.so.3 release/
        - docker cp builder:/usr/lib/libzmq.so.3.0.0 release/
        - docker cp builder:/mqtt release/
        # build release image
        - docker build -t edgepro/mb-mqtt:$$arch --no-cache=true -f release/Dockerfile.$$arch-pack release/.
        - docker push edgepro/mb-mqtt:$$arch
        # clean up
        - docker rm -f builder
        - docker rmi -f builder:$$arch

matrix:
    arch:
        - armhf
