sudo: required

language: c

services:
    - docker
env:
    DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
    - export TZ=Asia/Taipei
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
    - sudo apt-get update -y
    - sudo apt-get install -y python-dev mosquitto mosquitto-clients

script:
    - docker info
    - docker-compose version
    #- docker build --no-cache=true -t conf -f conf/Dockerfile.x86 .
    #- docker run -it conf
    #- docker build --no-cache=true -t test -f test/Dockerfile.x86 .
    #- docker run -it test
    #---------------------- PACKING -----------------------------------
    # build cache
    - docker build -t golang:x86-cache -f release/Dockerfile.x86-cache .
    # build builder
    - docker build -t builder:x86 --no-cache=true -f release/Dockerfile.x86-build .
    - docker run -itd --name=builder builder:x86
    # copy binary to release folder
    - docker cp builder:/mqtt release/
    # build release image
    - docker build -t edgepro/mb-mqtt:x86 --no-cache=true -f release/Dockerfile.x86-pack release/.
    #---------------------- SHELL TEST -------------------------------------
    - docker-compose -f docker-compose.x86 up -d
    - sleep 20
    - ./test.sh
    - docker-compose -f docker-compose.x86 logs
    - docker-compose -f docker-compose.x86 stop

notifications:
    email: false