package mqroute

const (
	keyTCPDefaultPort            = "psmbtcp.default_port"
	keyMinConnectionTimout       = "psmbtcp.min_connection_timeout"
	keyMqttDeviceID              = "mqtt.deviceid"
	keyMqttScheme                = "mqtt.scheme"
	keyMqttHost                  = "mqtt.host"
	keyMqttPort                  = "mqtt.port"
	keyMqttUsername              = "mqtt.username"
	keyMqttPassword              = "mqtt.password"
	keyMqttPubQos                = "mqtt.pub_qos"
	keyMqttSubQos                = "mqtt.sub_qos"
	keyMqttCleanSession          = "mqtt.enable_clean_session"
	keyMqttOrder                 = "mqtt.ensure_order"
	keyMqttWill                  = "mqtt.enable_will"
	keyMqttWillTopic             = "mqtt.will_topic"
	keyMqttWillPayload           = "mqtt.will_payload"
	keyMqttWillQos               = "mqtt.will_qos"
	keyMqttWillRetain            = "mqtt.will_retained"
	keyMqttKeepAlive             = "mqtt.keep_alive_interval"
	keyMqttPingTimeout           = "mqtt.wait_pong_timeout"
	keyMqttConnTimeout           = "mqtt.connection_timeout"
	keyMqttReconnectInterval     = "mqtt.max_reconnect_period"
	keyMqttAutoReconnect         = "mqtt.enable_auto_reconnect"
	keyMqttDepthSize             = "mqtt.offline_publish_queue_size"
	keyMqttWriteTimeout          = "mqtt.write_timeout"
	keyMqttSubTimeout            = "mqtt.sub_timeout"
	keyMqttVersion               = "mqtt.version"
	keyMqttIAM                   = "mqtt.iam"
	defaultTCPDefaultPort        = "502"
	defaultMinConnectionTimout   = 200000
	defaultMqttDeviceID          = "mydevice01"
	defaultMqttScheme            = "tcp"
	defaultMqttHost              = "iot.eclipse.org"
	defaultMqttPort              = 1883
	defaultMqttUsername          = ""
	defaultMqttPassword          = ""
	defaultMqttPubQos            = 1
	defaultMqttSubQos            = 1
	defaultMqttCleanSession      = true
	defaultMqttOrder             = true
	defaultMqttWill              = false
	defaultMqttWillTopic         = ""
	defaultMqttWillPayload       = ""
	defaultMqttWillQos           = 0
	defaultMqttWillRetain        = false
	defaultMqttKeepAliveInterval = 30
	defaultMqttPingTimeout       = 10
	defaultMqttConnTimeout       = 30
	defaultMqttReconnectInterval = 10
	defaultMqttAutoReconnect     = true
	defaultMqttDepthSize         = 1000
	defaultMqttWriteTimeout      = 30
	defaultMqttSubTimeout        = 30 // ms
	defaultMqttVersion           = "0.0.1"
	defaultMqttIAM               = "mqtt"
)
