# armhf
FROM armv7/armhf-ubuntu:16.04
MAINTAINER Taka Wang <taka@cmwang.net>

ENV CONF_SOCKET "/etc/mb-socket"
ENV EP_BACKEND "consul.cmwang.net:8500"

# add binary
ADD libzmq.so.3.0.0 /usr/lib/
ADD libzmq.so.3 /usr/lib/
ADD mqtt /usr/bin/
ADD config.toml ${CONF_SOCKET}/

#EXPOSE 1883

CMD /usr/bin/mqtt